#+title: Workbook
#+author: Ioannis Eleftheriou

* Table of Contents :TOC:
- [[#chapter-1-functions-and-data][Chapter 1 Functions and Data]]
  - [[#11][1.1]]
  - [[#12][1.2]]
  - [[#13][1.3]]
  - [[#14][1.4]]
  - [[#15][1.5]]
  - [[#16][1.6]]
  - [[#17][1.7]]
  - [[#18][1.8]]
  - [[#19][1.9]]
  - [[#110][1.10]]
  - [[#111][1.11]]
  - [[#112][1.12]]
  - [[#113][1.13]]
  - [[#114][1.14]]
  - [[#115][1.15]]
  - [[#116][1.16]]
  - [[#117][1.17]]
  - [[#118][1.18]]
  - [[#119][1.19]]
  - [[#120][1.20]]
  - [[#121][1.21]]
  - [[#122][1.22]]
  - [[#123][1.23]]
  - [[#124][1.24]]
  - [[#125][1.25]]
  - [[#126][1.26]]
  - [[#127][1.27]]
- [[#chapter-2-lists][Chapter 2 Lists]]
  - [[#21][2.1]]
  - [[#22][2.2]]
  - [[#23][2.3]]
  - [[#24][2.4]]
  - [[#25][2.5]]
  - [[#26][2.6]]

* Chapter 1 Functions and Data
** 1.1
[...] Use your knowledge of arithmetic to fill in the missing item

*** Solution
|            13 |
|             3 |
|             / |
|             3 |
|             3 |
|           -48 |
| $\frac{5}{3}$ |
|             0 |
|             - |
| $\frac{2}{3}$ |
|             2 |

** 1.2

[...] Put an "S" if it is a symbol, "I" if it is an integer, or "N" if it is some other kind of number.
*** Solution
| S |
| I |
| S |
| S |
| I |
| N |
| S |
| S |
| S |
| I |
| I |
| S |

** 1.3
Fill in the result of each computation

*** Solution
| T   |
| NIL |
| NIL |
| NIL |
| T   |
| T   |
| NIL |

** 1.4
Define a SUB2 function that subtracts two from its input.

*** Solution
#+begin_src lisp
(defun sub2 (num)
  (- num 2))
#+end_src

** 1.5
Show how to write TWOP in terms of ZEROP and SUB2

*** Solution
#+begin_src lisp
(defun twop (num)
  (zerop (sub2 num)))
#+end_src
** 1.6
The HALF function returns a number that is one-half of its input. Show how to define HALF two different ways.

*** Solution
#+begin_src lisp
(defun half (num)
  (/ num 2))
#+end_src

#+begin_src lisp
(defun half (num)
  (* num 0.5))
#+end_src
** 1.7
Write a MULTI-DIGIT-P predicate that returns true if its input is

*** Solution
#+begin_src lisp
(defun multi-digit-p (num)
  (> num 9))
#+end_src
** 1.8
What does this function do to a number?

*** Solution
Multiplies by -1.
** 1.9
Write a predicate TWOMOREP that returns T if its first input is exactly two more than its second input. Use the ADD2 function in your definition of TWOMOREP.

*** Solution
#+begin_src lisp
(defun twomorep (n1 n2)
  (= n2 (add2 n1)))
#+end_src
** 1.10
Find a way to write the TWOMOREP predicate using SUB2 instead of ADD2.

*** Solution
#+begin_src lisp
(defun twomorep (n1 n2)
  (= n1 (sub2 n2)))
#+end_src
** 1.11
The average of two numbers is half their sum.  Write the AVERAGE function.

*** Solution
#+begin_src lisp
(defun average (n1 n2)
  (/ (+ n1 n2) 2))
#+end_src

** 1.12
Write a MORE-THAN-HALF-P predicate that returns T if its first input
is more than half of its second input.

*** Solution
#+begin_src lisp
(defun more-than-half-p (n1 n2)
  (> n1 (/ n2 2)))
#+end_src
** 1.13
The following function returns the same result no matter what its input. What result does it return?

*** Solution
#+begin_src lisp
(defun testp (something)
  (symbolp (numberp something)))

(testp 100) ;=> t
(testp t) ;=> t
(testp nil) ;=> t
#+end_src
** 1.14
Fill in the results of the following computations
*** Solutions
| T                |
| NIL              |
| UNBOUND-VARIABLE |
** 1.15
Write a predicate NOT-ONEP that returns T if its input is anything other than one.

*** Solution
#+begin_src lisp
(defun not-onep (num)
  (not (= num 1)))
#+end_src

** 1.16
Write the predicate NOT-PLUSP that returns T if its input is not greater
than zero.

*** Solution
#+begin_src lisp
(defun not-plusp (num)
  (not (> num 0)))
#+end_src

** 1.17
Some earlier Lisp dialects did not have the EVENP primitive; they only had ODDP. Show how to define EVENP in terms of ODDP.

*** Solution
#+begin_src lisp
(defun evenp (num)
  (not (oddp num)))
#+end_src

** 1.18
Under what condition does this predicate function return T?

#+begin_src lisp
(lambda (num)
  (zerop (add1 (add1 num))))
#+end_src

*** Solution
When input is -2.

** 1.19
What result does the function below produce when given the input NIL? What about the input T? Will all data flow through this function unchanged? What result is produced for the input RUTABAGA?

#+begin_src lisp
(lambda (input) (not (not input)))
#+end_src

*** Solution
+ When input is NIL, output is T.
+ Not all data will flow through this function unchanged.

#+begin_src lisp
(defun rutabaga-function (something)
  (not (not something)))

(rutabaga-function 'rutabaga) ;=> t
#+end_src

+ Result for the symbol RUTABAGA is t.
** 1.20
A truth function is a function whose inputs and output are truth values, that is, true or false. NOT is a truth function. (Even though NOT accepts other inputs besides T or NIL, it only cares if its input is true or not.) Write XOR, the exclusive-or truth function, which returns T when one of its inputs is NIL and the other is T, but returns NIL when both are NIL or both are T.

*** Solution
#+begin_src lisp
(defun xor (n1 n2)
  (not (equal n1 n2)))
#+end_src

** 1.21
What is wrong with each of these functions?

#+begin_src lisp
(lambda (n)
  (add1 (zerop n)))
#+end_src

#+begin_src lisp
(lambda (n1 n2)
  (equal (+ 1 2)))
#+end_src

#+begin_src lisp
(lambda (n1 n2)
  (symbolp (not n1 n2)))
#+end_src
*** Solution
+ TYPE-ERROR
+ SIMPLE-PROGRAM-ERROR (EQUAL function requires two inputs)
+ SIMPLE-PROGRAM-ERROR (NOT function requires a single input)

** 1.22
Are all predicates functions? Are all functions predicates?

*** Solution
Yes. No.

** 1.23
Which built-in predicates introduced in this chapter have names that do not end in "P"?

*** Solution
EQUAL, <, >.

** 1.24
Is NUMBER a number? Is SYMBOL a symbol?

*** Solution
No. Yes.

** 1.25
Why is FALSE true in Lisp?

*** Solution
FALSE is a symbol, not a boolean value.

** 1.26
True or false: (a) All predicates accept T or NIL as input; (b) all predicates produce T or NIL as output.

*** Solution
a) False
b) True

** 1.27
Give an example of the use of EVENP that would cause a wrong-type-input error. Give an example that would cause a wrong-number-of-inputs error.

*** Solution

Wrong type of input
#+begin_src lisp
(evenp 'something)
#+end_src

Wrong number of inputs.
#+begin_src lisp
(evenp)
#+end_src
* Chapter 2 Lists
For drawing cons diagrams first load the following into the REPL.

#+begin_src lisp
(ql:quickload :draw-cons-tree)
#+end_src

** 2.1
Show how the list (TO BE OR NOT TO BE) would be represented in computer memory by drawing its cons cell representation

*** Solution
#+begin_src lisp
(TO BE OR NOT TO BE)
; [o|o]---[o|o]---[o|o]---[o|o]---[o|o]---[o|/]
;  |       |       |       |       |       |
;  TO      BE      OR     NOT      TO      BE
#+end_src
** 2.2
Which of these are well-formed lists? That is, which ones have properly balanced parentheses?
#+begin_src lisp
(A B (C)
((A) (B))
A B ) (C D)
(A (B (C))
(A (B (C)))
(((A) (B)) (C))
#+end_src

*** Solution
#+begin_src lisp
(A B (C)
((A) (B)) ; ok
A B ) (C D)
(A (B (C))
(A (B (C))) ;ok
(((A) (B)) (C)) ;ok
#+end_src

** 2.3
Draw the cons cell representation of the list (PLEASE (BE MY) VALENTINE).

*** Solution
#+begin_src lisp
; [o|o]---[o|o]---[o|/]
;  |       |       |
; PLEASE   |      VALENTINE
;          |
;         [o|o]---[o|/]
;          |       |
;          BE      MY
#+end_src
** 2.4
What is the parenthesis notation for this cons cell structure?

#+begin_src lisp
; [o|o]---[o|/]
;  |       |
;  |      [o|o]---[o|/]
;  |       |       |
;  |      FLOWERS CHOCHOLATES
;  |      
; [o|o]---[o|/]
;  |       |
; BOWS    ARROWS
#+end_src

*** Solution
#+begin_src lisp
((BOWS ARROWS) (FLOWERS CHOCHOLATES))
#+end_src
** 2.5
How many elements do each of the following lists have?

*** Solution
#+begin_src lisp
(length '(open the pod bay doors hal))
 ; => 6 (3 bits, #x6, #o6, #b110)

(length '((open) (the pod bay doors) hal))
 ; => 3 (2 bits, #x3, #o3, #b11)

(length '((1 2 3) (4 5 6) (7 8 9) (10 11 12)))
 ; => 4 (3 bits, #x4, #o4, #b100)

(length '((one) for all (and (two (for me)))))
 ; => 4 (3 bits, #x4, #o4, #b100)

(length '((q spades)
          (7 hearts)
          (6 clubs)
          (5 diamonds)
          (2 diamonds)))
 ; => 5 (3 bits, #x5, #o5, #b101)

(length '((pennsylvania (the keystone state))
          (new-jersey (the garden state))
          (massachussets (the bay state))
          (florida (the sunshine state))
          (new-york (the empire state))
          (indiana (the hoosier state))))
 ; => 6 (3 bits, #x6, #o6, #b110)
#+end_src

** 2.6
Match each list on the left with a corresponding list on the right by
substituting NIL for () wherever possible. Pay careful attention to levels of parenthesization.

*** Solution
#+begin_src lisp
() ;== NIL
(()) ;== (NIL)
((())) ;== ((NIL))
(() ()) ;== (NIL NIL)
(() (())) ;== (NIL (NIL))
#+end_src
